matchmaker/urls.py
from django.urls import path

from . import views

app_name = "matchmaker"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("teams", views.TeamsView.as_view(), name="teams"),
    path("tournament", views.TournamentView.as_view(), name="tournament"),
]

urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("matchmaker.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

matchmaker/views.py
from django import forms
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from pydantic import BaseModel

from matchmaker.teams import Team, make_teams
from matchmaker.tournament import MatchUpdate, Tournament, count_wins, make_tournament


class TeamsForm(forms.Form):
    team_size = forms.IntegerField(
        label="Spieler pro Team",
        min_value=1,
        required=True,
        widget=forms.NumberInput(
            attrs={
                "value": "2",
                "class": "min-w-full",
                "size": 1,
            }
        ),
    )
    player_groups = forms.CharField(
        label="Mitspieler",
        required=True,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Alejandro\nFernando\nRoberto\n...",
                "class": "min-w-full",
                "cols": 1,
            }
        ),
    )


class Session(BaseModel):
    team_size: int | None = None
    player_groups: str | None = None
    teams: list[Team] | None = None
    tournament: Tournament | None = None


class IndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        """Show a `TeamsForm` form for inputting team size and player names."""
        return render(request, "matchmaker/index.html", {"form": TeamsForm()})

    def post(self, request: HttpRequest) -> HttpResponse:
        """Flush session, put inputs from `TeamsForm` form and redirect to the teams view."""
        form = TeamsForm(request.POST)
        if not form.is_valid():
            return HttpResponseBadRequest()

        request.session.flush()
        request.session["team_size"] = int(form.cleaned_data["team_size"])
        request.session["player_groups"] = form.cleaned_data["player_groups"]
        # request.session["player_groups"] = [
        #     line.strip()
        #     for line in form.cleaned_data["player_groups"].splitlines()
        # ]
        return HttpResponseRedirect(reverse("matchmaker:teams"))


class HTTPResponseHXRedirect(HttpResponseRedirect):
    def __init__(self, *args, **kwargs):  # noqa: ANN002, ANN003
        super().__init__(*args, **kwargs)
        self["HX-Redirect"] = self["Location"]
        self.status_code = 200


class TeamsView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        """Generate teams and show them in a view."""
        session = Session(**request.session)
        if session.team_size is None or session.player_groups is None:
            return HttpResponseBadRequest()

        teams = make_teams(session.team_size, session.player_groups)
        request.session["teams"] = teams
        return render(request, "matchmaker/teams.html", {"teams": teams})

    def post(self, request: HttpRequest) -> HttpResponse:
        """Generate tournament and redirect to the tournament view."""
        session = Session(**request.session)
        if session.teams is None:
            return HttpResponseBadRequest()

        request.session["tournament"] = make_tournament(session.teams).model_dump()
        return HTTPResponseHXRedirect(reverse("matchmaker:tournament"))


class TournamentView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        """Show overview over the tournament (all rounds). TODO: Show scoreboard."""
        session = Session(**request.session)
        if session.teams is None or session.tournament is None:
            return HttpResponseBadRequest()

        return render(
            request,
            "matchmaker/tournament.html",
            {
                "tournament": session.tournament,
                "scores": count_wins(session.teams, session.tournament),
            },
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        match_update = MatchUpdate.from_post(request.POST)
        session = Session(**request.session)
        if session.teams is None or session.tournament is None:
            return HttpResponseBadRequest()

        try:
            session.tournament.set_match_result(match_update)
        except TypeError:  # Trying to set match result for `Break` match:
            return HttpResponseBadRequest()

        request.session["tournament"] = session.tournament.model_dump()
        # request.session.modified = True
        return render(
            request,
            "matchmaker/tournament.html",
            {
                "tournament": session.tournament,
                "scores": count_wins(session.teams, session.tournament),
            },
        )

matchmaker/templates/matchmaker/index.html
{% extends "base.html" %}

{% block title %}
  Matchmaker
{% endblock title %}

{% block heading %}
  Matchmaker
{% endblock heading %}

{% block content %}
  <form action="{% url 'matchmaker:index' %}" method="post" class="mx-4">
    {% csrf_token %}
    {% for field in form %}
      <div class="mb-4">
        {{ field.errors }}
        <div class="block font-bold text-gray-700">{{ field.label_tag }}</div>
        {{ field }}
      </div>
    {% endfor %}
    <div class="mx-auto max-w-fit">
      <button class="btn" type="submit">Teams Aufstellen</button>
    </div>
  </form>
{% endblock content %}

matchmaker/templates/matchmaker/teams.html
{% extends "base.html" %}

{% block title %}
  Matchmaker: Teams
{% endblock title %}

{% block heading %}
  Teams
{% endblock heading %}

{% block content %}
  <div class="mx-auto max-w-fit">
    <div class="inline-grid grid-cols-1">
      {% for team in teams %}
        <div class="p-2">
          <div class="p-1 flex flex-wrap justify-evenly w-full bg-{{ team.hue }}-300 rounded-md shadow">
            {% for player in team.members %}<span class="mx-2 capitalize">{{ player }}</span>{% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="mx-auto max-w-fit">
    <div class="inline-grid grid-cols-2">
      <button class="btn" onclick="window.location.reload()">Teams Neu Würfeln</button>
      <button class="btn"
              hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
              hx-post="{{ request.path }}">Neues Turnier Erstellen</button>
    </div>
  </div>
{% endblock content %}

matchmaker/templates/matchmaker/tournament.html
{% extends "base.html" %}

{% block title %}
  Matchmaker: Turnierübersicht
{% endblock title %}

{% block heading %}
  Turnierübersicht
{% endblock heading %}

{% block content %}
  <h3 class="pt-1 text-xl text-center border-b">Runden</h3>
  <div class="inline-grid grid-cols-1 min-w-full">
    {% for round in tournament.rounds %}
      <details {% if round.state == "CURRENT" %}open{% endif %}>
        <summary class="text-center">
          Runde {{ forloop.counter }} <span class="{% if round.state == 'DONE' %}text-green-500{% else %}text-white{% endif %}">✓</span>
        </summary>
        <div class="flex justify-center">
          <div class="inline-grid grid-cols-round">
            {% for match in round.matches %}
              {% if match.get_type == "PlayedMatch" %}
                <div class="flex justify-end p-2">
                  <div class="p-1 w-full flex flex-wrap justify-evenly items-center bg-{{ match.left.hue }}-300 rounded-md shadow">
                    {% for player in match.left.members %}
                      <span class="mx-2 capitalize">{{ player }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="flex items-center">
                  <input class="m-1"
                         type="radio"
                         name="result_{{ forloop.parentloop.counter0 }}_{{ forloop.counter0 }}"
                         value="LEFT_WON"
                         {% if match.result == "LEFT_WON" %}checked{% endif %}
                         hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                         hx-vals='{"round": {{ forloop.parentloop.counter0 }}, "match": {{ forloop.counter0 }}}'
                         hx-target="body"
                         hx-post="{{ request.path }}">
                  <input class="m-1"
                         type="radio"
                         name="result_{{ forloop.parentloop.counter0 }}_{{ forloop.counter0 }}"
                         value="RIGHT_WON"
                         {% if match.result == "RIGHT_WON" %}checked{% endif %}
                         hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                         hx-vals='{"round": {{ forloop.parentloop.counter0 }}, "match": {{ forloop.counter0 }}}'
                         hx-target="body"
                         hx-post="{{ request.path }}">
                </div>
                <div class="flex items-center p-2">
                  <div class="p-1 w-full flex flex-wrap justify-evenly items-center bg-{{ match.right.hue }}-300 rounded-md shadow">
                    {% for player in match.right.members %}
                      <span class="mx-2 capitalize">{{ player }}</span>
                    {% endfor %}
                  </div>
                </div>
              {% elif match.get_type == "Break" %}
                <div class="flex justify-center items-center p-2">
                  <div class="p-1 flex flex-wrap justify-evenly w-full items-center bg-{{ match.team.hue }}-300 rounded-md shadow">
                    {% for player in match.team.members %}
                      <span class="mx-2 capitalize">{{ player }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="flex col-start-3 justify-center items-center mx-2 text-gray-500">(Pause)</div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </details>
    {% endfor %}
  </div>

  <h3 class="pt-1 text-xl text-center border-b">Tabelle</h3>
  <div class="mx-auto max-w-fit">
    {% for team, score in scores.items %}
      <div class="p-2">
        <div class="p-1 grid grid-cols-scores w-full bg-{{ team.hue }}-300 rounded-md shadow">
          <span class="flex justify-evenly">
            {% for player in team.members %}<span class="px-2 capitalize">{{ player }}</span>{% endfor %}
          </span>
          <span class="pr-2 pl-6">{{ score }}</span>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="text-lg">
  <head>
    <link rel="shortcut icon"
          type="image/png"
          href="{% static 'favicon.png' %}" />
    <meta name="description"
          content="Create random round robin tournaments with randomized teams and track scores on a scoreboard.">
    <meta name="keywords" content="Random, Tournament, Scoreboard">
    <title>
      {% block title %}
        TITLE
      {% endblock title %}
    </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    {% tailwind_preload_css %}
    {% tailwind_css %}
  </head>
  <body>
    <header class="grid grid-cols-3 py-2 px-4 bg-gray-100 border-b">
      <a class="col-start-2 mx-auto max-w-fit"
         href='{% url "matchmaker:index" %}'>
        <h2 class="text-2xl">
          {% block heading %}
            HEADING
          {% endblock heading %}
        </h2>
      </a>
      <a title="Github"
         class="flex items-center ml-auto"
         href="https://github.com/kwie98/matchmaker">
        <svg class="h-6 fill-gray-500"
             viewBox="0 0 98 96"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M48.854 0C21.839 0 0 22 0 49.217c0 21.756 13.993 40.172 33.405 46.69 2.427.49 3.316-1.059 3.316-2.362 0-1.141-.08-5.052-.08-9.127-13.59 2.934-16.42-5.867-16.42-5.867-2.184-5.704-5.42-7.17-5.42-7.17-4.448-3.015.324-3.015.324-3.015 4.934.326 7.523 5.052 7.523 5.052 4.367 7.496 11.404 5.378 14.235 4.074.404-3.178 1.699-5.378 3.074-6.6-10.839-1.141-22.243-5.378-22.243-24.283 0-5.378 1.94-9.778 5.014-13.2-.485-1.222-2.184-6.275.486-13.038 0 0 4.125-1.304 13.426 5.052a46.97 46.97 0 0 1 12.214-1.63c4.125 0 8.33.571 12.213 1.63 9.302-6.356 13.427-5.052 13.427-5.052 2.67 6.763.97 11.816.485 13.038 3.155 3.422 5.015 7.822 5.015 13.2 0 18.905-11.404 23.06-22.324 24.283 1.78 1.548 3.316 4.481 3.316 9.126 0 6.6-.08 11.897-.08 13.526 0 1.304.89 2.853 3.316 2.364 19.412-6.52 33.405-24.935 33.405-46.691C97.707 22 75.788 0 48.854 0z" />
        </svg>
      </a>
    </header>
    <div class="px-4 mx-auto max-w-screen-sm">
      {% block content %}
        CONTENT
      {% endblock content %}
    </div>
  </body>
</html>